# ------------------------------------------------------------------------------
#  Copyright Matt Borland 2023.
#  Copyright Christopher Kormanyos 2023.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: up
  range: '50...100'
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: 75%
        threshold: 10%
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
    patch:
      default:
        target: 75%
        threshold: 25%

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no
