////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

= Building the Library
:idprefix: build_

== B2

Run the following commands to clone the latest versions of Boost and Charconv, prepare the Boost.Build system for use, and build the libraries with C++11 as the default standard:
[source, bash]
----
git clone https://github.com/boostorg/boost
cd boost
git submodule update --init
cd libs
git clone https://github.com/cppalliance/charconv
cd ..
./bootstrap
./b2 cxxstd=11
----

To install the development environment, run:

[source, bash]
----
sudo ./b2 install cxxstd=11
----

== vcpkg

Run the following commands to clone the latest version of Charconv and install it using vcpkg:
[source, bash]
----
git clone https://github.com/cppalliance/charconv
cd charconv
vcpkg install charconv --overlay-ports=ports/charconv
----

Any required Boost packages that do not already exist will be installed automatically.

== Conan

Run the following commands to clone the latest version of Charconv and build a boost_charconv package using your default profile:
[source, bash]
----
git clone https://github.com/cppalliance/charconv
conan create charconv/conan --build missing
----

The package will be put in the local Conan cache along with all direct and transitive dependencies.

TIP: Since Charconv only depends on a few header-only Boost libraries, you can save time by requesting header-only Boost:

[source, bash]
----
conan create charconv/conan -o 'boost*:header_only=True' --build missing
----

After the package is built, you can use it in your own projects.
For example, using a `conanfile.txt`:

[source, bash]
----
[requires]
boost_charconv/1.0.0
----

== Header Only
To use as header-only; that is, to eliminate the requirement to link a program to a static or dynamic Boost.Charconv library, simply place the following line in *exactly one* new or existing source file in your project.

[source, c++]
----
#include <boost/charconv/src.hpp>
----

IMPORTANT: MSVC users must also define the macro BOOST_CHARCONV_NO_LIB to disable auto-linking.
