////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

= to_chars
:idprefix: to_chars_

== to_chars overview
[source, c++]
----
struct to_chars_result
{
    char* ptr;
    int ec;

    friend constexpr bool operator==(const to_chars_result& lhs, const to_chars_result& rhs) noexcept;
    friend constexpr bool operator!=(const to_chars_result& lhs, const to_chars_result& rhs) noexcept;
};

template <typename Integral>
BOOST_CHARCONV_CONSTEXPR to_chars_result(char* first, char* last, Integral value, int base = 10) noexcept;

template <typename Integral>
BOOST_CHARCONV_CONSTEXPR to_chars_result<bool>(char* first, char* last, Integral value, int base) noexcept = delete;
----

== to_chars_result
* ptr - points to the first character
* ec - the error code. Valid values from <cerrno> are:
** 0 - successful parsing
** EINVAL - invalid argument
** ERANGE - result out of range (e.g. overflow)
* operator== - compares the value of ptr and ec for equality
* operator!= - compares the value of ptr and ec for inequality

== to_chars
* first, last - pointers to the character buffer
* value - the value to be paresed into the buffer
* base - the integer base to use. Must be between 2 and 36 inclusive
* from_chars for integral type is constexpr (BOOST_CHARCONV_CONSTEXPR is defined) when compiled using `-std=c++14` or newer and a compiler with `__builtin_ is_constant_evaluated`

== to_chars for integral types
* All built-in integral types are allowed except bool which is deleted
* These functions have been tested to support `__int128` and `unsigned __int128` when compiling with `-std=gnu++11` or newer

== Examples

=== Basic Usage
[source, c++]
----
char buffer[64] {};
int v = 42;
to_chars_result r = boost::charconv::to_chars(buffer, buffer + sizeof(buffer) - 1, v);
assert(r.ec == 0);
assert(!strcmp(buffer, "42")); // strcmp returns 0 on match
----

=== Hexadecimal
[source, c++]
----
char buffer[64] {};
int v = 42;
to_chars_result r = boost::charconv::to_chars(buffer, buffer + sizeof(buffer) - 1, v, 16);
assert(r.ec == 0);
assert(!strcmp(buffer, "2a")); // strcmp returns 0 on match
----

=== ERANGE
[source, c++]
----
char buffer[3] {};
int v = -1234;
to_chars_result r = boost::charconv::to_chars(buffer, buffer + sizeof(buffer) - 1, v, 16);
assert(r.ec == ERANGE);
----
In the event of ERANGE to_chars_result.ptr is first
